export const s = {
  card: 'group flex flex-1 flex-col rounded-xl border border-border bg-card shadow-sm overflow-hidden transition-all duration-200 hover:shadow-lg',
  imageLink: 'relative block aspect-square overflow-hidden bg-muted/30',
  image: 'object-cover transition-transform duration-300 group-hover:scale-105',
  placeholder: 'flex h-full flex-col items-center justify-center gap-2 text-muted-foreground/30',
  placeholderIcon: 'h-10 w-10',
  placeholderText: 'text-xs',
  discount: 'absolute left-3 top-3 rounded-md bg-red-500 px-2 py-0.5 text-xs font-semibold text-white',
  favoriteButton: 'absolute right-2 top-2 z-10 flex h-8 w-8 items-center justify-center rounded-full bg-white/80 backdrop-blur-sm shadow-sm transition-all duration-150 hover:bg-white hover:scale-110',
  favoriteIcon: 'h-4 w-4 transition-colors duration-150',
  favoriteIconActive: 'fill-red-500 text-red-500',
  favoriteIconInactive: 'text-muted-foreground',
  content: 'flex flex-1 flex-col gap-1.5 p-4 pt-3 border-t border-border',
  tags: 'flex flex-wrap gap-1',
  tag: 'text-[10px] px-1.5 py-0 border-primary/15 bg-primary/5 text-primary',
  name: 'text-sm leading-snug text-card-foreground transition-colors duration-150 group-hover:text-primary line-clamp-2',
  category: 'text-xs text-muted-foreground',
  rating: 'flex items-center gap-1',
  ratingCount: 'text-xs text-muted-foreground',
  footer: 'flex items-end justify-between mt-auto pt-3',
  priceGroup: 'flex flex-col',
  price: 'text-lg font-bold text-foreground',
  oldPrice: 'text-xs text-muted-foreground line-through',
  cartButton: 'h-9 w-9 rounded-lg bg-primary text-primary-foreground hover:bg-primary/90',
  cartButtonIcon: 'h-4 w-4',
  outOfStock: 'text-xs text-destructive font-medium',
  skeleton: 'h-full w-full animate-pulse rounded-md bg-muted',
};
